### ISSUE TITLE
[Request] Add a classic UI theme

### ISSUE THREAD

**Issue by loca-file** [spicetify/spicetify-themes#1015]
Spotify has changed their UI and I don't like it. I  even tried to edit the "app.enable-developer-mode" line in the "prefs" file that is located in the Spotify folder of AppData, but it didn't work. I even tried older versions of Spotify, but the Spicetify Marketplace doesn't seem to be working.
Is there an extension or a theme that can restore the old UI?

**Comment by harbassan** [comment]
No there aren't any extensions or themes to restore it, the best you can get is enabling compact mode on the left sidebar to have something like this which at least makes the left sidebar kind of similar:
![image](https://github.com/spicetify/spicetify-themes/assets/84175605/159947f1-aee2-472e-93bf-f81de8725753)

Unfortunately making a theme/extension that returns to classic UI would require a lot of effort because the library is completely different now. There is a custom app called [betterLibrary,](https://github.com/Sowgro/betterLibrary) which I haven't tried so I don't know if it works, but you can try that if you want a page similar to the old library.

Downgrading should work tho, and if marketplace isn't working you can try the older version of it.

And ofcourse you can always try and make your own theme, which could atleast try and get the visuals similair.
