### ISSUE TITLE
Playlist buttons in the wrong place and not working 

### ISSUE THREAD

**Issue by chamdar-13** [spicetify/spicetify-themes#787]
🔍 Have you checked Spicetify.app page for your issue?
 I have checked the FAQ
🔍 Is there already an issue for your problem?
 I have checked older issues, open and closed
ℹ Environment / Computer Info
- Spotify version: 1.1.88.612.gcc529952
- Spicetify version: 2.10.1

**Describe the bug**
playlist buttons don't work, and the "create playlist" and "liked songs" buttons are at the bottom of the sidebar, the actual playlist sidebar is under everything for some reason. 
**To Reproduce**
applying spicetify themes breaks the sidebar (so spicetify apply)

**Expected behavior**
The sidebar to be functioning as normal, and for the "create playlist" and "liked songs" buttons to be at the top of the sidebar where they usually are. 

Screenshots
![Spotify Premium 25_06_2022 02_28_22](https://user-images.githubusercontent.com/108148928/175644215-1b2d423e-bcb1-4882-9e99-f19bbf49ece6.png)
The playlists, create playlist button and the liked songs button are all in the bottom left corner of spotify.

**Comment by phthal0** [comment]
i have the same issue here, 
![image](https://user-images.githubusercontent.com/84078890/175761730-f2776ffc-c5ae-49d1-952d-ef6725aca8cb.png)

spotify randomly breaks when i reopen the app. the playlist scroll bar is visible for a few seconds before it moves to the very right hand side, which enables the page as a whole to be scrolled downwards to display additional playlists at the bottom. (as seen in op's screenshot). furthermore, (at least in my case) playlists on the left hand side aren't clickable at all. with some themes, if you hover over the playlist name you can see it respond, but you can't click it to go to the playlist (marketplace, library, home etc are still accessible)

https://user-images.githubusercontent.com/84078890/175761812-de578592-f742-4fa6-9a4d-17b6c85bbfa8.mp4
i've been trying to find some sort of causation for this issue in the last few days, considering that i use blockthespot with spicetify as well, but i don't think it's related. 

(sorry, not too sure about github etiquette when it comes to reporting on issues. apologies if i should have opened another issue instead of commenting on this one.)

**Comment by Phonixed456** [comment]
I have this exact issue
![image](https://user-images.githubusercontent.com/75176016/175790680-7e867ce5-992c-40f1-b4a1-a89eb08c84f5.png)

**Comment by Hansworst85** [comment]
![image](https://user-images.githubusercontent.com/76130308/176804697-269d03ac-d17d-4167-90c3-f53b82cdd436.png)
Yeah same thing goes for me, hope someone will find a solution for this.

**Comment by kyrie25** [comment]
1. This *was* a CLI issue, not a theme issue
2. Issue has already been resolved in Spicetify CLI v2.10.2

Closing issue.
