### ISSUE TITLE
[Sleek]  Selecting Playlist on Deeper Theme Does Not Bold Playlist Name

### ISSUE THREAD

**Issue by snyde875** [spicetify/spicetify-themes#794]
When using the "Deeper" theme from Sleek, hovering your mouse over a playlist does not bold the playlist name to indicate you're hovering over it. In addition, selecting a playlist does not bold it either. Below are images showing examples of this.

The image below is an example using the "Wealthy" theme. In this example, you can see that the "Hard House" playlist title on the left column is correctly turned to a green font to indicate that it is the selected playlist. 
![image](https://user-images.githubusercontent.com/46146906/176965942-5f292d12-648f-46f9-8196-54fe782c8848.png)

The image below is an example using the "Deeper" theme. In this example, there's no visual indicator to indicate that the "Hard House" playlist is selected like in the "Wealthy" theme. I think that the font should either be bolded or changed to a different color like in the "Wealthy" theme and that the absence of such an indicator is a bug. This might not be the case, but I think it might be.
![image](https://user-images.githubusercontent.com/46146906/176966152-fc2f980d-ec08-4fb8-bfca-a90a1a4cac4b.png)

**Comment by sxppro** [comment]
This is because the text and subtext colours are the same for the Deeper theme. If you change the text colour (in `Sleek/color.ini` where you installed your Spicetify themes), you can see a different colour when your hover and select a playlist.
```ini
[Deeper]
; Light blue on dark background
text               = 4f9a87 ; <-- this one
subtext            = 4f9a87
```

If you don't like how the option changes text colour in other parts of the app, go into `Sleek/user.css` and add:
```css
.main-rootlist-rootlistItemOverlay:hover ~ .main-rootlist-rootlistItemLink {
  color: #ffffff; /* <-- replace with hex code of your chosen colour */
}
```

(the above snippet may become outdated as Spotify updates their app)
