### ISSUE TITLE
[Ziro] Rose Pine Dawn

### ISSUE THREAD

**Issue by Pusagii** [spicetify/spicetify-themes#930]
All the buttons show up with the original Spotify colors, so they are black rather than what it is supposed to be. 
Hovering over playlist and other things also make it turn black, I do not know if I am doing anything wrong though. 
I have the most recent versions of both of the applications, and I followed the install instructions

Here are images of it:
![image](https://github.com/spicetify/spicetify-themes/assets/133341918/9f3cb9e1-31ed-4277-9f24-039c4cbb88a1)

**Comment by harbassan** [comment]
The reason for this is because the theme isn't compatible/styled for the new sidebar layout yet.  You can go back to the old sidebar layout if you want by going into experimental features and disabling your library x. Otherwise, you're going to have to wait until someone decides to contribute and update the theme.

**Comment by Pusagii** [comment]
Thank you, this worked!! I was scared I couldn't use this cute theme www

Hope someone fixes it for the new library though
